spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/ci_hospital}
    username: ${SPRING_DATASOURCE_USERNAME:ci_user}
    password: ${SPRING_DATASOURCE_PASSWORD:ci_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: smtp.office365.com
    port: 587
    username: ${MAIL_USERNAME:no-reply@hospitalprovincial.es}
    password: ${MAIL_PASSWORD:Zan50068}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  base-url: ${APP_BASE_URL:http://localhost:5173}
  token-expiry-hours: ${TOKEN_EXPIRY_HOURS:72}
  mail-from: no-reply@hospitalprovincial.es
  signatures-path: ${SIGNATURES_PATH:./signatures}
  pdf-path: ${PDF_PATH:./pdfs}
  keystore-path: ${KEYSTORE_PATH:certs/chpc-keystore.p12}
  keystore-password: ${KEYSTORE_PASSWORD:chpc2026}
  keystore-alias: ${KEYSTORE_ALIAS:chpc-sign}
  mtls-enabled: true
  mtls-port: 8444
  mtls-truststore-path: certs/truststore.p12
  mtls-truststore-password: changeit

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID:ACb7951f4cada5f3a765c7a5f84b652349}
  auth-token: ${TWILIO_AUTH_TOKEN:56c70065f292b0463bdbc54d6eb23822}
  from-number: ${TWILIO_FROM_NUMBER:+15206857458}

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:dev_secret_cambia_en_produccion_minimo_32_chars_debe_tener_al_menos_64_para_ser_seguro_hs512_chpc_2026}
  expiration-ms: ${JWT_EXPIRATION_MS:28800000}

his:
  base-url: ${HIS_BASE_URL:http://localhost:9090}
  timeout-ms: 5000

apikewan:
  enabled: ${APIKEWAN_ENABLED:true}
  base-url: ${APIKEWAN_BASE_URL:https://apikewan.chpcs.local}
  server-id: ${APIKEWAN_SERVER_ID:serverjavacidigital}
  issuer: ${APIKEWAN_ISSUER:serverjavacidigital}
  kid: ${APIKEWAN_KID:HoalAdios123.}
  audience: ${APIKEWAN_AUDIENCE:api-hospital}
  scope: ${APIKEWAN_SCOPE:citas.read}
  private-key: ${APIKEWAN_PRIVATE_KEY:}
  private-key-path: ${APIKEWAN_PRIVATE_KEY_PATH:secrets/apikewan-private-key.pem}
  timeout-ms: ${APIKEWAN_TIMEOUT_MS:5000}
  truststore-path: ${APIKEWAN_TRUSTSTORE_PATH:certs/truststore.p12}
  truststore-password: ${APIKEWAN_TRUSTSTORE_PASSWORD:changeit}
  truststore-type: ${APIKEWAN_TRUSTSTORE_TYPE:PKCS12}

logging:
  level:
    com.chpc: DEBUG
    org.springframework.security: INFO
    org.springframework.ldap: DEBUG

# ── Active Directory Properties ──
ldap:
  enabled: true
  url: ldap://dc01.chpcs.local:389
  base: dc=chpcs,dc=local
  domain: chpcs.local
  required-group: DEP02_1536_ACCESO_CIDIGITAL
  user-search-filter: (sAMAccountName={0})
  group-search-base: ""
  group-search-filter: (member={0})
